services:
  # Backend API
  - type: web
    name: gestor-licencias-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/scripts/run-backup.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: gestor-licencias-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://gestor-licencias-frontend.onrender.com

  # Frontend
  - type: web
    name: gestor-licencias-frontend
    env: static
    plan: free
    buildCommand: cd gestor-licencias-frontend && npm install && npm run build
    staticPublishPath: ./gestor-licencias-frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://gestor-licencias-api.onrender.com

databases:
  - name: gestor-licencias-db
    databaseName: gestor_licencias
    user: gestor_licencias_user 